### ISSUE TITLE
eps reliability plots cannot be parsed

### ISSUE THREAD

**Issue by SpaceMeerkat** [SoFiA-Admin/SoFiA-2#95]
I've ran into an issue whereby I cannot open or convert the output `rel.eps` files because the postscript cannot be parsed. The `skellam.eps` files can however be opened using photoshop or converted using ps2png or ps2pdf. 

I'm unfamiliar with debugging postscript, but the problem seems to be related to the diagonal dashed lines you see in the reliability plots...

An example error report from attempting `$ps2pdf`:

```
eps
Error: /undefined in -inf
Operand stack:
   400.0
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1988   1   3   %oparray_pop   --nostringval--   1977   1   3   %oparray_pop   1833   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:731/1123(ro)(G)--   --dict:0/20(G)--   --dict:99/200(L)--
Current allocation mode is local
Current file position is 90105
GPL Ghostscript 9.50: Unrecoverable error, exit code 1
```

Which appears to be this section of the postscript (after all the marker positions, towards the end of the file):

```
gsave
0.8 0.8 0.8 rgb
np 400 750 m 700 750 l 700 1050 l 400 1050 l cp clip
547.75 972.73 3.49 1.62 33.60 1.88 ellipse
[2 2] 0 setdash
547.75 972.73 6.98 3.25 33.60 1.88 ellipse
[0.5 1.5] 0 setdash
547.75 972.73 10.47 4.87 33.60 1.88 ellipse
grestore
gsave
0.5 0.5 0.5 rgb
[3 3] 0 setdash
np 400 750 m 700 750 l 700 1050 l 400 1050 l cp clip
400.00 -inf m
700.00 -inf l s
np 414 1030 m
0.5 0.5 0.5 rgb
(minSNR = 0.0) show
0.9 0.9 0.9 rgb
[0.5 2] 0 setdash
np 400 750 m 700 750 l 700 1050 l 400 1050 l cp clip
400.00 689.71 m
700.00 1254.77 l s
442.01 760.00 m
```

Any help on this would be greatly appreciated!

**Comment by SpaceMeerkat** [comment]
EDIT: This was fixed by setting `reliability.minSNR > 0`. Whether this is by chance or not I haven't figured out though..

**Comment by SpaceMeerkat** [comment]
It appears that the issue does persist even when using `reliability.minSNR > 0`. You can hardcode the `-inf` terms above to something like 0 and the parsescript is usable by an editor like photoshop, but at the cost of having no dashed threshold and hence, lots of false positive detections. 

e.g. setting the `-inf` terms to 0:

![Example_rel](https://user-images.githubusercontent.com/32263989/221555049-c8a8da38-0855-4c1e-bd42-6bd0b7288486.png)

**Comment by SoFiA-Admin** [comment]
Thank you for reporting this problem. The reason for the value of `-inf` is that the reliability plot is logarithmic and hence supplying `minSNR <= 0` will result in the position of the dashed SNR line in the plot being undefined. I have fixed this problem by first checking that `minSNR > 0` before inserting the line (see 3da904934b08955c0201f5bcda793ca4912196ab).

That being said, I would generally advise against running SoFiA with a non-finite minSNR, as you will end up with a large number of false positives, as evident from the reliability plot in your post. Typically, a `minSNR` of roughly 3 is a sensible choice (assuming the beam size is accurately defined in the FITS header, as it is needed to calculate SNR). Otherwise, false positives with low SNR in regions of parameter space that are only sparsely populated with detections will end up in your final catalogue, as their reliability cannot be accurately calculated due to the sparseness of positive and negative detections along the periphery of the main noise cloud in the reliability plot.

**Comment by SoFiA-Admin** [comment]
Looking at your plot again, I just realised that `minSNR = 3` in your example. Does the `-inf` problem still occur when you set `minSNR` to a meaningful positive value? If yes then this could potentially indicate that the `BMAJ` and `BMIN` keywords in the FITS header are not set to the correct values. If one of those were zero then you would also end up with `minSNR = 0` and hence `-inf` in the EPS file, as the beam area is needed to define SNR.

**Comment by SpaceMeerkat** [comment]
Thanks for the replies! Yes, unfortunately the `-inf` problem still persists with a meaningful `minSNR`.. I'll check the beam info in the header, as I seem to recall a lot of warnings about the beam info when I use `pipeline.verbose`, so it could be that. I'll report back!

**Comment by SpaceMeerkat** [comment]
I had a quick look and some of the cubes I have are missing the `BMAJ` and `BMIN` values, just like you said. So that must be the issue, thanks for spotting that!

**Comment by SoFiA-Admin** [comment]
No worries, this would indeed explain why there are so many false detections all across the reliability plot, as `minSNR` effectively becomes zero. If you manually add the correct beam information to the header and rerun SoFiA, the problem should disappear and you should be seeing a sensible SNR cut-off in the reliability plot.

**Comment by SpaceMeerkat** [comment]
Yeah, just confirming here that that indeed solved the problem after a few tests and I'm now seeing the sensible SNR cutoff line as expected. Thanks!
